### ISSUE TITLE
Possibility of using with zilliqa-js-sdk?

### ISSUE THREAD

**Issue by csajedi** [KZen-networks/multisig-schnorr#28]
Hello, 

I want to demonstrate TSS for Zilliqa and not sure about how plausible it is. I understand that it is now possible to compile Rust to webassembly and then it could be used in the same environments as the zilliqa-javascript-sdk. Is this presently practical to attempt or request? I am experienced with c/c++ but not rust or webassembly. How will developers use the TSS scheme with Zilliqa as it stands? There is no Rust sdk.

**Comment by omershlo** [comment]
Hi! 
a lot to unpack here, 
the short answer is that it is very much possible and recently @oleiba have done something similar for binanace chain to connect tss to binance sdk : https://github.com/KZen-networks/binance-thresh-wallet 
In fact what he did was just a minor example of what actually can be done: he defined rust api for two functions: key generation and signing, and wrote binding to call them from binance sdk (@oleiba correct me if I'm wrong). 
The good news is that this repo contains all you need in terms of cryptography. The bad news is that this is all it contains. 

btw, there is also a work in progress to have TSS on wasm - we started from ECDSA (check emerald-city) but now we know it will be possible for Schnorr sigs.

**Comment by omershlo** [comment]
@talbeerysec / @oleiba do you plan to add support for zilliqa-js-sdk ? if you do can you estimate when? maybe @csajedi can help or you can help him ?

**Comment by csajedi** [comment]
@omershlo thank you for your reply, I was in touch with Tal via telegram and he informed me that the goal is to integrate the Schnorr TSS found here into the Zilliqa-Javascript-SDK. Work has started and the hope is to finish it by mid-june.

**Comment by oleiba** [comment]
Hi @csajedi take a look at our forked version of Zilliqa JS SDK, it now supports two-party Schnorr signatures:
https://github.com/KZen-networks/Zilliqa-JavaScript-Library
